import { createHash } from "node:crypto";
const TERMINAL = new Set(["completed", "failed", "cancelled", "killed"]);
const SECRET = /(authorization\s*[:=]|bearer\s+\S+|(?:api[_-]?key|password|private[_-]?key|secret|token)\s*[:=]|BEGIN [A-Z]+ PRIVATE KEY)/iu;
const sha = (s) => createHash("sha256").update(s).digest("hex");
function text(v, label, max, required = false) { if (typeof v !== "string" || (required && !v) || v.length > max || SECRET.test(v)) throw new Error(label + " is invalid or contains sensitive material"); return v; }
function strings(v, label) { if (v === undefined) return []; if (!Array.isArray(v) || v.length > 32) throw new Error(label + " must contain at most 32 entries"); return v.map((x) => text(x, label + " entry", 2000, true)); }
function artifactList(v) { if (v === undefined) return []; if (!Array.isArray(v) || v.length > 32) throw new Error("artifacts must contain at most 32 entries"); return v.map((x) => { if (!x || typeof x !== "object" || Array.isArray(x)) throw new Error("artifact must be an object"); const out = { kind: text(x.kind, "artifact kind", 64, true), location: text(x.location, "artifact location", 2048, true) }; if (x.sha256 !== undefined && !/^[a-f0-9]{64}$/u.test(x.sha256)) throw new Error("artifact sha256 must be a full SHA-256 digest"); if (x.description !== undefined) out.description = text(x.description, "artifact description", 1000); if (x.sha256) out.sha256 = x.sha256; return out; }); }
function render(r) { return ["# Genbio run " + r.recordId, "", "Project: " + r.project, "", "Summary", r.summary, "", "Significance", r.significance || "Not provided.", "", "Limitations", ...(r.limitations.length ? r.limitations.map((x) => "- " + x) : ["- Not provided."]), "", "Next Steps", ...(r.nextSteps.length ? r.nextSteps.map((x) => "- " + x) : ["- Not provided."]), "", "Evidence", JSON.stringify(r.evidence, null, 2), "", "Artifacts", ...(r.artifacts.length ? r.artifacts.map((x) => "- " + x.kind + ": " + x.location + (x.sha256 ? " (" + x.sha256 + ")" : "")) : ["- None."]), ""].join("\n"); }
export function createFinalizationRuntime({ publisher = null } = {}) {
  function finalize(run, args) { if (!run || !TERMINAL.has(run.status)) throw new Error("Genbio run must reach a terminal state before finalization"); if (run.finalization) return run.finalization; const semantic = { project: text(args.project, "project", 200, true), summary: text(args.summary, "summary", 12000, true), significance: args.significance === undefined ? "" : text(args.significance, "significance", 6000), limitations: strings(args.limitations, "limitations"), nextSteps: strings(args.next_steps, "next_steps"), artifacts: artifactList(args.artifacts) }; const evidence = { runId: run.runId, target: run.target, operation: run.operation, status: run.status, startedAt: run.startedAt, finishedAt: run.finishedAt, policyHash: run.policyHash || null, node: run.node || null, partition: run.partition || null, envelope: run.envelope || null, resources: run.resources || null, remoteRunDir: typeof run.remoteRunDir === "string" ? run.remoteRunDir : null, terminalEvidence: run.terminalEvidence || run.computeTerminalStatus || run.status }; const recordId = "genbio-" + run.runId + "-" + sha(JSON.stringify({ evidence, semantic })).slice(0, 16); const rendered = render({ recordId, ...semantic, evidence }); if (rendered.length > 32000) throw new Error("curated memory record exceeds 32000 characters"); run.finalization = Object.freeze({ recordId, hash: sha(rendered), text: rendered, finalizedAt: Date.now() }); run.memory = { ...(run.memory || {}), status: "ready", error: null }; return run.finalization; }
  async function publish(run, ownerHandle) { if (!run.finalization) throw new Error("finalize the Genbio run before publishing it"); if (run.memory && run.memory.status === "published") return { ok: true, status: "published" }; if (!publisher || typeof publisher.publish !== "function") { run.memory = { ...(run.memory || {}), status: "unavailable", error: "OpenViking publisher is unavailable" }; return { ok: false, status: "unavailable", error: run.memory.error }; } try { const out = await publisher.publish(ownerHandle, run.finalization); const status = out && out.status === "duplicate" ? "published" : ((out && out.status) || (out && out.ok ? "published" : "failed")); run.memory = { ...(run.memory || {}), status, error: (out && out.error) || null, traceId: (out && out.traceId) || null, openVikingSessionId: (out && out.sessionId) || null }; return { ok: out && out.ok === true || status === "published", status, ...(out && out.error ? { error: out.error } : {}) }; } catch (error) { run.memory = { ...(run.memory || {}), status: "failed", error: String(error && error.message || error) }; return { ok: false, status: "failed", error: run.memory.error }; } }
  return Object.freeze({ finalize, publish });
}
